=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Fruteria DONE/fruteria.dtd
<!ELEMENT fruteria (fruta, verdura, ofertas)+>

<!ELEMENT fruta (platanos, manzanas?, (uvas | sandia)+)>
<!ELEMENT platanos EMPTY>
<!ELEMENT manzanas EMPTY>
<!ELEMENT uvas EMPTY>
<!ELEMENT sandia EMPTY>

<!ELEMENT verdura EMPTY>

<!ELEMENT ofertas (#PCDATA | referencia)*>
<!ELEMENT referencia EMPTY>



<!ATTLIST fruteria  nombre CDATA #REQUIRED
                    direccion CDATA #IMPLIED
                    telefono CDATA #FIXED "555 345 244">

<!ATTLIST verdura tipo (apio | brocoli | lechuga) #REQUIRED>
<!ATTLIST fruta variedad IDREFS #IMPLIED>

<!ATTLIST referencia tipoFruta IDREF #REQUIRED>

<!ENTITY % codigoFruta "codigoFruta ID #REQUIRED">
<!ATTLIST platanos %codigoFruta;>
<!ATTLIST manzanas %codigoFruta;>
<!ATTLIST uvas %codigoFruta;>
<!ATTLIST sandia %codigoFruta;>

<!ENTITY mejorPrecio "El mejor precio garantizado">

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Fruteria DONE/fruteria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruteria SYSTEM "fruteria.dtd">
<fruteria nombre="La banana" telefono="555 345 244">

    <fruta variedad="pla man uv san">
        <platanos codigoFruta="pla" />
        <manzanas codigoFruta="man"/>
        <uvas codigoFruta="uv"/>
        <sandia codigoFruta="san"/>
    </fruta>

    <verdura tipo="brocoli"/>

    <ofertas>2x1 &mejorPrecio;
        <referencia tipoFruta="man"/>
    </ofertas>

</fruteria>
