=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/pokemon.dtd
<!ELEMENT pokemonMovie (personajes, combates)>

<!ELEMENT personajes (personaje)+>
<!ELEMENT personaje (nombre, edad, pokemon*, amigos?, (bueno | malo))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT pokemon (#PCDATA)>
<!ELEMENT amigos EMPTY>
<!ELEMENT bueno EMPTY>
<!ELEMENT malo EMPTY>


<!ELEMENT combates (#PCDATA | lugar)*>
<!ELEMENT lugar EMPTY>


<!ATTLIST pokemonMovie  nombre CDATA #REQUIRED
                        numero CDATA #IMPLIED
                        dueñoFranquicia CDATA #FIXED "Nintendo">
                        
<!ATTLIST personajes elenco IDREFS #REQUIRED>
<!ATTLIST nombre aka ID #REQUIRED>
<!ATTLIST amigos codAmigo IDREF #IMPLIED>

<!ATTLIST lugar localizacion (playa | montaña | bosque) #REQUIRED>

<!ENTITY favorito "El mejor pokemon del mundo">
<!ENTITY % enemigo "enemigo IDREF #IMPLIED">
<!ATTLIST bueno %enemigo;>
<!ATTLIST malo %enemigo;>

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Pokemon/pokemon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokemonMovie SYSTEM "pokemon.dtd">
<pokemonMovie nombre="pokemon y la venganza de mewtwo"  dueÃ±oFranquicia="Nintendo">
    <personajes elenco="gorras pelos pesao">
        <personaje>
            <nombre aka="gorras">ash</nombre>
            <edad>10</edad>
            <pokemon>Pikachu &favorito;</pokemon>
            <pokemon>Bulbasaur</pokemon>
            <pokemon>Charmander</pokemon>
            <bueno />
        </personaje>
        <personaje>
            <nombre aka="pelos">jessy</nombre>
            <edad>23</edad>
            <pokemon>Arbok</pokemon>
            <amigos codAmigo="pesao"/>
            <malo enemigo="gorras" />
        </personaje>
        <personaje>
            <nombre aka="pesao">james</nombre>
            <edad>23</edad>
            <pokemon>Arbok</pokemon>
            <amigos codAmigo="pelos"/>
            <malo enemigo="gorras"/>
        </personaje>
    </personajes>
    <combates>la pelea de la playa
        <lugar localizacion="playa" />
    </combates>
</pokemonMovie>
