=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/prueba/prueba.dtd
<!ELEMENT juicios (caso, acusados)>

<!ELEMENT caso (#PCDATA | resolucion)*>
<!ELEMENT resolucion EMPTY>

<!ELEMENT acusados (nombreAcusado, edad, reincidente?, (hombre | mujer))+>
<!ELEMENT nombreAcusado (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT reincidente EMPTY>
<!ELEMENT hombre EMPTY>
<!ELEMENT mujer EMPTY>

<!ATTLIST juicios lugar CDATA #FIXED "juzgado provincial de Tarragona">

<!ATTLIST caso acusado IDREF #REQUIRED>
<!ATTLIST acusados losMasPeligrosos IDREFS #IMPLIED>
<!ATTLIST nombreAcusado codigo ID #REQUIRED>

<!ATTLIST resolucion fallo (a_favor | en_contra | suspendido) #REQUIRED>

<!ENTITY inocente "El jurado lo declara ">

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/prueba/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE juicios SYSTEM "prueba.dtd">

<juicios lugar="juzgado provincial de Tarragona">
    <caso acusado="jpere">La fruteria Gonzales acusa a Juan Perea de hurto.
        <resolucion fallo="a_favor" />
    </caso>
    <acusados losMasPeligrosos="elPipa laLoca">
        <nombreAcusado codigo="jpere">
            Juan Perea
        </nombreAcusado> 
        <edad>
            23
        </edad>
        <hombre/>
        <nombreAcusado codigo="elPipa">
            Alfonso El pipa
        </nombreAcusado> 
        <edad>
            30
        </edad>
        <reincidente />
        <hombre/>
        <nombreAcusado codigo="laLoca">
            La loca
        </nombreAcusado> 
        <edad>
            43
        </edad>
        <mujer/>
    </acusados>
</juicios>
