=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Bebidas/bebidas.dtd
<!ELEMENT licoreria (cocteles, botella, ofertas+)>

<!ELEMENT cocteles (margarita, longIsland?, (wiskyHielo | wiskySolo))>
<!ELEMENT margarita EMPTY>
<!ELEMENT longIsland EMPTY>
<!ELEMENT wiskyHielo EMPTY>
<!ELEMENT wiskySolo EMPTY>

<!ELEMENT botella EMPTY>

<!ELEMENT ofertas (#PCDATA | referencia)*>
<!ELEMENT referencia EMPTY>

<!ATTLIST licoreria nombre CDATA #REQUIRED
                    direccion CDATA #IMPLIED
                    telefono CDATA #FIXED "555 321 123">

<!ATTLIST cocteles variedad IDREFS #REQUIRED>

<!ATTLIST botella tamanio (pequeÃ±a | mediana | grande) #IMPLIED>
<!ATTLIST referencia articulo IDREF #REQUIRED>

<!ENTITY % codigo "codigo ID #REQUIRED">
<!ATTLIST margarita %codigo;>
<!ATTLIST longIsland %codigo;>
<!ATTLIST wiskyHielo %codigo;>
<!ATTLIST wiskySolo %codigo;>

<!ENTITY especial "OFERTA ESPECIAL, SOLO HOY">

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Bebidas/bebidas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE licoreria SYSTEM "bebidas.dtd">
<licoreria nombre="El cacharro" direccion="La de siempre" telefono="555 321 123">
    <cocteles variedad="mar lon wisS">
        <margarita codigo="mar"/>
        <longIsland codigo="lon"/>
        <wiskySolo codigo="wisS"/>
    </cocteles>
    <botella tamanio="grande"/>
    <ofertas>2x1
        <referencia articulo="mar" />
    </ofertas>
    <ofertas>el 3ยบ gratis &especial;
        <referencia articulo="wisS" />
    </ofertas>
</licoreria>
