=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Liga de balonmano/ligaDeBalonmano.dtd
<!ELEMENT ligaBalonmano (equipos, partidos)>
<!ELEMENT equipos (equipo)+>
<!ELEMENT equipo (nombre, localidad, entrenador?, (federado | noFederado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT federado EMPTY>
<!ELEMENT noFederado EMPTY>


<!ELEMENT partidos (partido)*>
<!ELEMENT partido (equipoLocal, equipoVisitante)>
<!ELEMENT equipoLocal (#PCDATA | victoria | derrota)*>
<!ELEMENT equipoVisitante (#PCDATA | victoria | derrota)*>
<!ELEMENT victoria EMPTY>
<!ELEMENT derrota EMPTY>

<!ATTLIST ligaBalonmano nombre CDATA #FIXED "Liga de campeones de Balonmano"
                        anio CDATA #REQUIRED
                        mascotaOficial CDATA #IMPLIED>

<!ATTLIST equipos favoritos IDREFS #IMPLIED>
<!ATTLIST equipo codEquipo ID #REQUIRED>

<!ATTLIST partido tipoDePista (cesped | tierraBatida | cemento) #REQUIRED>

<!ENTITY % nombreEquipo "nombre IDREF #REQUIRED">
<!ATTLIST equipoLocal %nombreEquipo;>
<!ATTLIST equipoVisitante %nombreEquipo;>

<!ENTITY MVP "Mejor entrenador de la temporada">

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/Liga de balonmano/ligaDeBalonmano.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaBalonmano SYSTEM "ligaDeBalonmano.dtd">
<ligaBalonmano nombre="Liga de campeones de Balonmano" anio="2023">
    <equipos favoritos="mbm bbs"> 
        <equipo codEquipo="bbs">
            <nombre>
                betis balonmano
            </nombre>
            <localidad>
                Sevilla
            </localidad>
            <entrenador>
                Bartolo &MVP;
            </entrenador>
            <federado />
        </equipo>
        <equipo codEquipo="mbm">
            <nombre>
                madrid balonmano
            </nombre>
            <localidad>
                madrid
            </localidad>
            <entrenador>
                Juan Robledo
            </entrenador>
            <federado />
        </equipo>
        <equipo codEquipo="rcb">
            <nombre>
                real club de balonmano
            </nombre>
            <localidad>
                Albacete
            </localidad>
            <noFederado/>
        </equipo>
    </equipos>
    <partidos>
        <partido tipoDePista="cesped">
            <equipoLocal nombre="rcb">12 - 4
                <victoria />
            </equipoLocal>
            <equipoVisitante nombre="mbm"> 4 - 12
                <derrota />
            </equipoVisitante>
        </partido>
    </partidos>
</ligaBalonmano>
