=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/EXAMEN/inmobiliaria.dtd
<!ELEMENT inmobiliaria (casas, ofertas)>

<!ELEMENT casas (casa)+>
<!ELEMENT casa (precio, tamanio, habitaciones, piscina?, (barrioRico | barrioPobre))>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT tamanio (#PCDATA)>
<!ELEMENT habitaciones (#PCDATA)>
<!ELEMENT piscina EMPTY>
<!ELEMENT barrioRico EMPTY>
<!ELEMENT barrioPobre EMPTY>

<!ELEMENT ofertas (oferta)*>
<!ELEMENT oferta (#PCDATA | refCasa)*>
<!ELEMENT refCasa EMPTY>

<!ATTLIST inmobiliaria  nombre CDATA #REQUIRED
                        direccion CDATA #FIXED "elCasuplonWapo.com">  

<!ATTLIST casas nuevas IDREFS #IMPLIED>

<!ATTLIST casa  tipo (piso | casa | chalet | mansion) #REQUIRED
                codCasa ID #REQUIRED>

<!ATTLIST refCasa casaDeReferencia IDREF #REQUIRED>

<!ENTITY ofertaEspecial "Oferta especial, solo por tiempo limitado, me la quitan de las manos!!">
<!ENTITY % vecinos "vecinos CDATA #IMPLIED">
<!ATTLIST barrioRico %vecinos;>
<!ATTLIST barrioPobre %vecinos;>

=== DaniPalacios93/ejerciciosLMSGI/pruebaExamen/EXAMEN/inmobiliaria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inmobiliaria SYSTEM "inmobiliaria.dtd">
<inmobiliaria nombre="el casuplón wapo" direccion="elCasuplonWapo.com">
    <casas nuevas="chalet1 casa1">
        <casa tipo="chalet" codCasa="chalet1">
            <precio>750.000</precio>
            <tamanio>200m²</tamanio>
            <habitaciones>7</habitaciones>
            <piscina />
            <barrioRico />
        </casa>
        <casa tipo="piso" codCasa="piso1">
            <precio>85.000</precio>
            <tamanio>70m²</tamanio>
            <habitaciones>3</habitaciones>
            <barrioPobre />
        </casa>
        <casa tipo="casa" codCasa="casa1">
            <precio>120.000</precio>
            <tamanio>98m²</tamanio>
            <habitaciones>5</habitaciones>
            <piscina />
            <barrioPobre />
        </casa>
    </casas>
    <ofertas>
        <oferta>Casa sin amueblar, 10% de rebaja ½
            <refCasa casaDeReferencia="casa1" />
        </oferta>
    </ofertas>
</inmobiliaria>
